### ISSUE TITLE
`structs_assert` can be simplified or omitted

### ISSUE THREAD

**Issue by Rangi42** [ISSOtm/rgbds-structs#10]
`structs_assert` tries to report the erroneous line number, but `__LINE__` will always expand to its internal line number within the macro.

It's also a single-use macro that could just be an inline `assert` or `fail` like other error checks.

**Comment by ISSOtm** [comment]
As mentioned in #12, it's *currently* a single-use macro, but I want it to be reusable elsewhere later.
You're right that the reported line number is useless as-is, though; it's printed in the file stack anyway. (If I wanted to get it right, I'd probably need an `equs` or something.)
